// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan.proto

package share

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ScanErrorCode int32

const (
	ScanErrorCode_ScanErrNone                ScanErrorCode = 0
	ScanErrorCode_ScanErrNetwork             ScanErrorCode = 1
	ScanErrorCode_ScanErrNotSupport          ScanErrorCode = 2
	ScanErrorCode_ScanErrSizeOverLimit       ScanErrorCode = 3
	ScanErrorCode_ScanErrPackage             ScanErrorCode = 4
	ScanErrorCode_ScanErrDatabase            ScanErrorCode = 5
	ScanErrorCode_ScanErrTimeout             ScanErrorCode = 6
	ScanErrorCode_ScanErrInProgress          ScanErrorCode = 7
	ScanErrorCode_ScanErrRegistryAPI         ScanErrorCode = 8
	ScanErrorCode_ScanErrFileSystem          ScanErrorCode = 9
	ScanErrorCode_ScanErrContainerAPI        ScanErrorCode = 10
	ScanErrorCode_ScanErrXrayAPI             ScanErrorCode = 11
	ScanErrorCode_ScanErrContainerExit       ScanErrorCode = 12
	ScanErrorCode_ScanErrAuthentication      ScanErrorCode = 13
	ScanErrorCode_ScanErrCertificate         ScanErrorCode = 14
	ScanErrorCode_ScanErrCanceled            ScanErrorCode = 15
	ScanErrorCode_ScanErrDriverAPINotSupport ScanErrorCode = 16
	ScanErrorCode_ScanErrImageNotFound       ScanErrorCode = 17
	ScanErrorCode_ScanErrAwsDownloadErr      ScanErrorCode = 18
	ScanErrorCode_ScanErrArgument            ScanErrorCode = 19
	ScanErrorCode_ScanErrSignatureScanError  ScanErrorCode = 20
)

var ScanErrorCode_name = map[int32]string{
	0:  "ScanErrNone",
	1:  "ScanErrNetwork",
	2:  "ScanErrNotSupport",
	3:  "ScanErrSizeOverLimit",
	4:  "ScanErrPackage",
	5:  "ScanErrDatabase",
	6:  "ScanErrTimeout",
	7:  "ScanErrInProgress",
	8:  "ScanErrRegistryAPI",
	9:  "ScanErrFileSystem",
	10: "ScanErrContainerAPI",
	11: "ScanErrXrayAPI",
	12: "ScanErrContainerExit",
	13: "ScanErrAuthentication",
	14: "ScanErrCertificate",
	15: "ScanErrCanceled",
	16: "ScanErrDriverAPINotSupport",
	17: "ScanErrImageNotFound",
	18: "ScanErrAwsDownloadErr",
	19: "ScanErrArgument",
	20: "ScanErrSignatureScanError",
}
var ScanErrorCode_value = map[string]int32{
	"ScanErrNone":                0,
	"ScanErrNetwork":             1,
	"ScanErrNotSupport":          2,
	"ScanErrSizeOverLimit":       3,
	"ScanErrPackage":             4,
	"ScanErrDatabase":            5,
	"ScanErrTimeout":             6,
	"ScanErrInProgress":          7,
	"ScanErrRegistryAPI":         8,
	"ScanErrFileSystem":          9,
	"ScanErrContainerAPI":        10,
	"ScanErrXrayAPI":             11,
	"ScanErrContainerExit":       12,
	"ScanErrAuthentication":      13,
	"ScanErrCertificate":         14,
	"ScanErrCanceled":            15,
	"ScanErrDriverAPINotSupport": 16,
	"ScanErrImageNotFound":       17,
	"ScanErrAwsDownloadErr":      18,
	"ScanErrArgument":            19,
	"ScanErrSignatureScanError":  20,
}

func (x ScanErrorCode) String() string {
	return proto.EnumName(ScanErrorCode_name, int32(x))
}
func (ScanErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type ScanObjectType int32

const (
	ScanObjectType_CONTAINER  ScanObjectType = 0
	ScanObjectType_HOST       ScanObjectType = 1
	ScanObjectType_IMAGE      ScanObjectType = 2
	ScanObjectType_PLATFORM   ScanObjectType = 3
	ScanObjectType_SERVERLESS ScanObjectType = 4
)

var ScanObjectType_name = map[int32]string{
	0: "CONTAINER",
	1: "HOST",
	2: "IMAGE",
	3: "PLATFORM",
	4: "SERVERLESS",
}
var ScanObjectType_value = map[string]int32{
	"CONTAINER":  0,
	"HOST":       1,
	"IMAGE":      2,
	"PLATFORM":   3,
	"SERVERLESS": 4,
}

func (x ScanObjectType) String() string {
	return proto.EnumName(ScanObjectType_name, int32(x))
}
func (ScanObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type ScanProvider int32

const (
	ScanProvider_Neuvector ScanProvider = 0
	ScanProvider_JFrogXray ScanProvider = 1
)

var ScanProvider_name = map[int32]string{
	0: "Neuvector",
	1: "JFrogXray",
}
var ScanProvider_value = map[string]int32{
	"Neuvector": 0,
	"JFrogXray": 1,
}

func (x ScanProvider) String() string {
	return proto.EnumName(ScanProvider_name, int32(x))
}
func (ScanProvider) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type ScanVulStatus int32

const (
	ScanVulStatus_Unpatched  ScanVulStatus = 0
	ScanVulStatus_FixExists  ScanVulStatus = 1
	ScanVulStatus_WillNotFix ScanVulStatus = 2
	ScanVulStatus_Unaffected ScanVulStatus = 3
)

var ScanVulStatus_name = map[int32]string{
	0: "Unpatched",
	1: "FixExists",
	2: "WillNotFix",
	3: "Unaffected",
}
var ScanVulStatus_value = map[string]int32{
	"Unpatched":  0,
	"FixExists":  1,
	"WillNotFix": 2,
	"Unaffected": 3,
}

func (x ScanVulStatus) String() string {
	return proto.EnumName(ScanVulStatus_name, int32(x))
}
func (ScanVulStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type ScanTypeMap struct {
	Vulnerability bool `protobuf:"varint,1,opt,name=Vulnerability" json:"Vulnerability,omitempty"`
	Signature     bool `protobuf:"varint,2,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *ScanTypeMap) Reset()                    { *m = ScanTypeMap{} }
func (m *ScanTypeMap) String() string            { return proto.CompactTextString(m) }
func (*ScanTypeMap) ProtoMessage()               {}
func (*ScanTypeMap) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ScanTypeMap) GetVulnerability() bool {
	if m != nil {
		return m.Vulnerability
	}
	return false
}

func (m *ScanTypeMap) GetSignature() bool {
	if m != nil {
		return m.Signature
	}
	return false
}

type ScanVulnerability struct {
	Name                  string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Score                 float32  `protobuf:"fixed32,2,opt,name=Score" json:"Score,omitempty"`
	Severity              string   `protobuf:"bytes,3,opt,name=Severity" json:"Severity,omitempty"`
	Description           string   `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	PackageNameDeprecated string   `protobuf:"bytes,5,opt,name=PackageNameDeprecated" json:"PackageNameDeprecated,omitempty"`
	PackageVersion        string   `protobuf:"bytes,6,opt,name=PackageVersion" json:"PackageVersion,omitempty"`
	FixedVersion          string   `protobuf:"bytes,7,opt,name=FixedVersion" json:"FixedVersion,omitempty"`
	Link                  string   `protobuf:"bytes,8,opt,name=Link" json:"Link,omitempty"`
	Vectors               string   `protobuf:"bytes,9,opt,name=Vectors" json:"Vectors,omitempty"`
	ScoreV3               float32  `protobuf:"fixed32,10,opt,name=ScoreV3" json:"ScoreV3,omitempty"`
	VectorsV3             string   `protobuf:"bytes,11,opt,name=VectorsV3" json:"VectorsV3,omitempty"`
	PublishedDate         string   `protobuf:"bytes,12,opt,name=PublishedDate" json:"PublishedDate,omitempty"`
	LastModifiedDate      string   `protobuf:"bytes,13,opt,name=LastModifiedDate" json:"LastModifiedDate,omitempty"`
	CPEs                  []string `protobuf:"bytes,14,rep,name=CPEs" json:"CPEs,omitempty"`
	CVEs                  []string `protobuf:"bytes,15,rep,name=CVEs" json:"CVEs,omitempty"`
	FeedRating            string   `protobuf:"bytes,16,opt,name=FeedRating" json:"FeedRating,omitempty"`
	InBase                bool     `protobuf:"varint,17,opt,name=InBase" json:"InBase,omitempty"`
	DBKey                 string   `protobuf:"bytes,18,opt,name=DBKey" json:"DBKey,omitempty"`
	FileName              string   `protobuf:"bytes,19,opt,name=FileName" json:"FileName,omitempty"`
	PackageName           string   `protobuf:"bytes,20,opt,name=PackageName" json:"PackageName,omitempty"`
}

func (m *ScanVulnerability) Reset()                    { *m = ScanVulnerability{} }
func (m *ScanVulnerability) String() string            { return proto.CompactTextString(m) }
func (*ScanVulnerability) ProtoMessage()               {}
func (*ScanVulnerability) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ScanVulnerability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanVulnerability) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ScanVulnerability) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *ScanVulnerability) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ScanVulnerability) GetPackageNameDeprecated() string {
	if m != nil {
		return m.PackageNameDeprecated
	}
	return ""
}

func (m *ScanVulnerability) GetPackageVersion() string {
	if m != nil {
		return m.PackageVersion
	}
	return ""
}

func (m *ScanVulnerability) GetFixedVersion() string {
	if m != nil {
		return m.FixedVersion
	}
	return ""
}

func (m *ScanVulnerability) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *ScanVulnerability) GetVectors() string {
	if m != nil {
		return m.Vectors
	}
	return ""
}

func (m *ScanVulnerability) GetScoreV3() float32 {
	if m != nil {
		return m.ScoreV3
	}
	return 0
}

func (m *ScanVulnerability) GetVectorsV3() string {
	if m != nil {
		return m.VectorsV3
	}
	return ""
}

func (m *ScanVulnerability) GetPublishedDate() string {
	if m != nil {
		return m.PublishedDate
	}
	return ""
}

func (m *ScanVulnerability) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *ScanVulnerability) GetCPEs() []string {
	if m != nil {
		return m.CPEs
	}
	return nil
}

func (m *ScanVulnerability) GetCVEs() []string {
	if m != nil {
		return m.CVEs
	}
	return nil
}

func (m *ScanVulnerability) GetFeedRating() string {
	if m != nil {
		return m.FeedRating
	}
	return ""
}

func (m *ScanVulnerability) GetInBase() bool {
	if m != nil {
		return m.InBase
	}
	return false
}

func (m *ScanVulnerability) GetDBKey() string {
	if m != nil {
		return m.DBKey
	}
	return ""
}

func (m *ScanVulnerability) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ScanVulnerability) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type ScanLayerResult struct {
	Digest  string               `protobuf:"bytes,1,opt,name=Digest" json:"Digest,omitempty"`
	Vuls    []*ScanVulnerability `protobuf:"bytes,2,rep,name=Vuls" json:"Vuls,omitempty"`
	Cmds    string               `protobuf:"bytes,3,opt,name=Cmds" json:"Cmds,omitempty"`
	Size    int64                `protobuf:"varint,4,opt,name=Size" json:"Size,omitempty"`
	Secrets *ScanSecretResult    `protobuf:"bytes,5,opt,name=Secrets" json:"Secrets,omitempty"`
}

func (m *ScanLayerResult) Reset()                    { *m = ScanLayerResult{} }
func (m *ScanLayerResult) String() string            { return proto.CompactTextString(m) }
func (*ScanLayerResult) ProtoMessage()               {}
func (*ScanLayerResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ScanLayerResult) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ScanLayerResult) GetVuls() []*ScanVulnerability {
	if m != nil {
		return m.Vuls
	}
	return nil
}

func (m *ScanLayerResult) GetCmds() string {
	if m != nil {
		return m.Cmds
	}
	return ""
}

func (m *ScanLayerResult) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ScanLayerResult) GetSecrets() *ScanSecretResult {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ScanModule struct {
	Name    string           `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version string           `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
	Source  string           `protobuf:"bytes,3,opt,name=Source" json:"Source,omitempty"`
	Vuls    []*ScanModuleVul `protobuf:"bytes,4,rep,name=Vuls" json:"Vuls,omitempty"`
	CPEs    []string         `protobuf:"bytes,5,rep,name=CPEs" json:"CPEs,omitempty"`
	File    string           `protobuf:"bytes,6,opt,name=File" json:"File,omitempty"`
}

func (m *ScanModule) Reset()                    { *m = ScanModule{} }
func (m *ScanModule) String() string            { return proto.CompactTextString(m) }
func (*ScanModule) ProtoMessage()               {}
func (*ScanModule) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *ScanModule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanModule) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ScanModule) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ScanModule) GetVuls() []*ScanModuleVul {
	if m != nil {
		return m.Vuls
	}
	return nil
}

func (m *ScanModule) GetCPEs() []string {
	if m != nil {
		return m.CPEs
	}
	return nil
}

func (m *ScanModule) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type ScanModuleVul struct {
	Name   string        `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Status ScanVulStatus `protobuf:"varint,2,opt,name=Status,enum=share.ScanVulStatus" json:"Status,omitempty"`
}

func (m *ScanModuleVul) Reset()                    { *m = ScanModuleVul{} }
func (m *ScanModuleVul) String() string            { return proto.CompactTextString(m) }
func (*ScanModuleVul) ProtoMessage()               {}
func (*ScanModuleVul) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *ScanModuleVul) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanModuleVul) GetStatus() ScanVulStatus {
	if m != nil {
		return m.Status
	}
	return ScanVulStatus_Unpatched
}

type ScanSecretLog struct {
	Type       string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
	File       string `protobuf:"bytes,3,opt,name=File" json:"File,omitempty"`
	RuleDesc   string `protobuf:"bytes,4,opt,name=RuleDesc" json:"RuleDesc,omitempty"`
	Suggestion string `protobuf:"bytes,5,opt,name=Suggestion" json:"Suggestion,omitempty"`
}

func (m *ScanSecretLog) Reset()                    { *m = ScanSecretLog{} }
func (m *ScanSecretLog) String() string            { return proto.CompactTextString(m) }
func (*ScanSecretLog) ProtoMessage()               {}
func (*ScanSecretLog) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *ScanSecretLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ScanSecretLog) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ScanSecretLog) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ScanSecretLog) GetRuleDesc() string {
	if m != nil {
		return m.RuleDesc
	}
	return ""
}

func (m *ScanSecretLog) GetSuggestion() string {
	if m != nil {
		return m.Suggestion
	}
	return ""
}

type ScanSecretResult struct {
	Error ScanErrorCode    `protobuf:"varint,1,opt,name=Error,enum=share.ScanErrorCode" json:"Error,omitempty"`
	Logs  []*ScanSecretLog `protobuf:"bytes,2,rep,name=Logs" json:"Logs,omitempty"`
}

func (m *ScanSecretResult) Reset()                    { *m = ScanSecretResult{} }
func (m *ScanSecretResult) String() string            { return proto.CompactTextString(m) }
func (*ScanSecretResult) ProtoMessage()               {}
func (*ScanSecretResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *ScanSecretResult) GetError() ScanErrorCode {
	if m != nil {
		return m.Error
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanSecretResult) GetLogs() []*ScanSecretLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ScanSetIdPermLog struct {
	Type     string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	File     string `protobuf:"bytes,2,opt,name=File" json:"File,omitempty"`
	Evidence string `protobuf:"bytes,3,opt,name=Evidence" json:"Evidence,omitempty"`
}

func (m *ScanSetIdPermLog) Reset()                    { *m = ScanSetIdPermLog{} }
func (m *ScanSetIdPermLog) String() string            { return proto.CompactTextString(m) }
func (*ScanSetIdPermLog) ProtoMessage()               {}
func (*ScanSetIdPermLog) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *ScanSetIdPermLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ScanSetIdPermLog) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ScanSetIdPermLog) GetEvidence() string {
	if m != nil {
		return m.Evidence
	}
	return ""
}

type ScanResult struct {
	Version            string               `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Error              ScanErrorCode        `protobuf:"varint,2,opt,name=Error,enum=share.ScanErrorCode" json:"Error,omitempty"`
	Namespace          string               `protobuf:"bytes,3,opt,name=Namespace" json:"Namespace,omitempty"`
	Vuls               []*ScanVulnerability `protobuf:"bytes,4,rep,name=Vuls" json:"Vuls,omitempty"`
	ContainerID        string               `protobuf:"bytes,5,opt,name=ContainerID" json:"ContainerID,omitempty"`
	HostID             string               `protobuf:"bytes,6,opt,name=HostID" json:"HostID,omitempty"`
	Registry           string               `protobuf:"bytes,7,opt,name=Registry" json:"Registry,omitempty"`
	Repository         string               `protobuf:"bytes,8,opt,name=Repository" json:"Repository,omitempty"`
	Tag                string               `protobuf:"bytes,9,opt,name=Tag" json:"Tag,omitempty"`
	Digest             string               `protobuf:"bytes,10,opt,name=Digest" json:"Digest,omitempty"`
	ImageID            string               `protobuf:"bytes,11,opt,name=ImageID" json:"ImageID,omitempty"`
	Layers             []*ScanLayerResult   `protobuf:"bytes,12,rep,name=Layers" json:"Layers,omitempty"`
	Envs               []string             `protobuf:"bytes,13,rep,name=Envs" json:"Envs,omitempty"`
	Labels             map[string]string    `protobuf:"bytes,14,rep,name=Labels" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platform           string               `protobuf:"bytes,15,opt,name=Platform" json:"Platform,omitempty"`
	PlatformVersion    string               `protobuf:"bytes,16,opt,name=PlatformVersion" json:"PlatformVersion,omitempty"`
	Author             string               `protobuf:"bytes,17,opt,name=Author" json:"Author,omitempty"`
	CVEDBCreateTime    string               `protobuf:"bytes,18,opt,name=CVEDBCreateTime" json:"CVEDBCreateTime,omitempty"`
	Modules            []*ScanModule        `protobuf:"bytes,19,rep,name=Modules" json:"Modules,omitempty"`
	Secrets            *ScanSecretResult    `protobuf:"bytes,20,opt,name=Secrets" json:"Secrets,omitempty"`
	Cmds               []string             `protobuf:"bytes,21,rep,name=Cmds" json:"Cmds,omitempty"`
	SetIdPerms         []*ScanSetIdPermLog  `protobuf:"bytes,22,rep,name=SetIdPerms" json:"SetIdPerms,omitempty"`
	Provider           ScanProvider         `protobuf:"varint,23,opt,name=Provider,enum=share.ScanProvider" json:"Provider,omitempty"`
	Size               int64                `protobuf:"varint,24,opt,name=Size" json:"Size,omitempty"`
	SignatureInfo      *ScanSignatureInfo   `protobuf:"bytes,25,opt,name=SignatureInfo" json:"SignatureInfo,omitempty"`
	Created            string               `protobuf:"bytes,26,opt,name=Created" json:"Created,omitempty"`
	ScanTypesRequested *ScanTypeMap         `protobuf:"bytes,27,opt,name=ScanTypesRequested" json:"ScanTypesRequested,omitempty"`
}

func (m *ScanResult) Reset()                    { *m = ScanResult{} }
func (m *ScanResult) String() string            { return proto.CompactTextString(m) }
func (*ScanResult) ProtoMessage()               {}
func (*ScanResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *ScanResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ScanResult) GetError() ScanErrorCode {
	if m != nil {
		return m.Error
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanResult) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ScanResult) GetVuls() []*ScanVulnerability {
	if m != nil {
		return m.Vuls
	}
	return nil
}

func (m *ScanResult) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *ScanResult) GetHostID() string {
	if m != nil {
		return m.HostID
	}
	return ""
}

func (m *ScanResult) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *ScanResult) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *ScanResult) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ScanResult) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ScanResult) GetImageID() string {
	if m != nil {
		return m.ImageID
	}
	return ""
}

func (m *ScanResult) GetLayers() []*ScanLayerResult {
	if m != nil {
		return m.Layers
	}
	return nil
}

func (m *ScanResult) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *ScanResult) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ScanResult) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ScanResult) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

func (m *ScanResult) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ScanResult) GetCVEDBCreateTime() string {
	if m != nil {
		return m.CVEDBCreateTime
	}
	return ""
}

func (m *ScanResult) GetModules() []*ScanModule {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *ScanResult) GetSecrets() *ScanSecretResult {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *ScanResult) GetCmds() []string {
	if m != nil {
		return m.Cmds
	}
	return nil
}

func (m *ScanResult) GetSetIdPerms() []*ScanSetIdPermLog {
	if m != nil {
		return m.SetIdPerms
	}
	return nil
}

func (m *ScanResult) GetProvider() ScanProvider {
	if m != nil {
		return m.Provider
	}
	return ScanProvider_Neuvector
}

func (m *ScanResult) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ScanResult) GetSignatureInfo() *ScanSignatureInfo {
	if m != nil {
		return m.SignatureInfo
	}
	return nil
}

func (m *ScanResult) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ScanResult) GetScanTypesRequested() *ScanTypeMap {
	if m != nil {
		return m.ScanTypesRequested
	}
	return nil
}

type SBOMMetadata struct {
	RootDirectory   string               `protobuf:"bytes,1,opt,name=RootDirectory" json:"RootDirectory,omitempty"`
	FilePaths       []string             `protobuf:"bytes,2,rep,name=FilePaths" json:"FilePaths,omitempty"`
	TrivyScanResult []*TrivyScanResponse `protobuf:"bytes,3,rep,name=TrivyScanResult" json:"TrivyScanResult,omitempty"`
}

func (m *SBOMMetadata) Reset()                    { *m = SBOMMetadata{} }
func (m *SBOMMetadata) String() string            { return proto.CompactTextString(m) }
func (*SBOMMetadata) ProtoMessage()               {}
func (*SBOMMetadata) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *SBOMMetadata) GetRootDirectory() string {
	if m != nil {
		return m.RootDirectory
	}
	return ""
}

func (m *SBOMMetadata) GetFilePaths() []string {
	if m != nil {
		return m.FilePaths
	}
	return nil
}

func (m *SBOMMetadata) GetTrivyScanResult() []*TrivyScanResponse {
	if m != nil {
		return m.TrivyScanResult
	}
	return nil
}

type ScanSignatureInfo struct {
	Verifiers             []string      `protobuf:"bytes,1,rep,name=Verifiers" json:"Verifiers,omitempty"`
	VerificationTimestamp string        `protobuf:"bytes,2,opt,name=VerificationTimestamp" json:"VerificationTimestamp,omitempty"`
	VerificationError     ScanErrorCode `protobuf:"varint,3,opt,name=VerificationError,enum=share.ScanErrorCode" json:"VerificationError,omitempty"`
}

func (m *ScanSignatureInfo) Reset()                    { *m = ScanSignatureInfo{} }
func (m *ScanSignatureInfo) String() string            { return proto.CompactTextString(m) }
func (*ScanSignatureInfo) ProtoMessage()               {}
func (*ScanSignatureInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *ScanSignatureInfo) GetVerifiers() []string {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

func (m *ScanSignatureInfo) GetVerificationTimestamp() string {
	if m != nil {
		return m.VerificationTimestamp
	}
	return ""
}

func (m *ScanSignatureInfo) GetVerificationError() ScanErrorCode {
	if m != nil {
		return m.VerificationError
	}
	return ScanErrorCode_ScanErrNone
}

type ScanRunningRequest struct {
	Type             ScanObjectType `protobuf:"varint,1,opt,name=Type,enum=share.ScanObjectType" json:"Type,omitempty"`
	ID               string         `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
	AgentID          string         `protobuf:"bytes,3,opt,name=AgentID" json:"AgentID,omitempty"`
	AgentRPCEndPoint string         `protobuf:"bytes,4,opt,name=AgentRPCEndPoint" json:"AgentRPCEndPoint,omitempty"`
}

func (m *ScanRunningRequest) Reset()                    { *m = ScanRunningRequest{} }
func (m *ScanRunningRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanRunningRequest) ProtoMessage()               {}
func (*ScanRunningRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *ScanRunningRequest) GetType() ScanObjectType {
	if m != nil {
		return m.Type
	}
	return ScanObjectType_CONTAINER
}

func (m *ScanRunningRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ScanRunningRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *ScanRunningRequest) GetAgentRPCEndPoint() string {
	if m != nil {
		return m.AgentRPCEndPoint
	}
	return ""
}

type ScanData struct {
	Error        ScanErrorCode     `protobuf:"varint,1,opt,name=Error,enum=share.ScanErrorCode" json:"Error,omitempty"`
	Buffer       []byte            `protobuf:"bytes,2,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	SbomMetadata *SBOMMetadata     `protobuf:"bytes,3,opt,name=SbomMetadata" json:"SbomMetadata,omitempty"`
	SBOMBuffer   []byte            `protobuf:"bytes,4,opt,name=SBOMBuffer,proto3" json:"SBOMBuffer,omitempty"`
	WorkloadMeta *WorkloadMetadata `protobuf:"bytes,5,opt,name=WorkloadMeta" json:"WorkloadMeta,omitempty"`
}

func (m *ScanData) Reset()                    { *m = ScanData{} }
func (m *ScanData) String() string            { return proto.CompactTextString(m) }
func (*ScanData) ProtoMessage()               {}
func (*ScanData) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *ScanData) GetError() ScanErrorCode {
	if m != nil {
		return m.Error
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanData) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *ScanData) GetSbomMetadata() *SBOMMetadata {
	if m != nil {
		return m.SbomMetadata
	}
	return nil
}

func (m *ScanData) GetSBOMBuffer() []byte {
	if m != nil {
		return m.SBOMBuffer
	}
	return nil
}

func (m *ScanData) GetWorkloadMeta() *WorkloadMetadata {
	if m != nil {
		return m.WorkloadMeta
	}
	return nil
}

type WorkloadMetadata struct {
	Name      string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=Namespace" json:"Namespace,omitempty"`
}

func (m *WorkloadMetadata) Reset()                    { *m = WorkloadMetadata{} }
func (m *WorkloadMetadata) String() string            { return proto.CompactTextString(m) }
func (*WorkloadMetadata) ProtoMessage()               {}
func (*WorkloadMetadata) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *WorkloadMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkloadMetadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ScanAppPackage struct {
	AppName    string `protobuf:"bytes,1,opt,name=AppName" json:"AppName,omitempty"`
	ModuleName string `protobuf:"bytes,2,opt,name=ModuleName" json:"ModuleName,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=Version" json:"Version,omitempty"`
	FileName   string `protobuf:"bytes,4,opt,name=FileName" json:"FileName,omitempty"`
}

func (m *ScanAppPackage) Reset()                    { *m = ScanAppPackage{} }
func (m *ScanAppPackage) String() string            { return proto.CompactTextString(m) }
func (*ScanAppPackage) ProtoMessage()               {}
func (*ScanAppPackage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *ScanAppPackage) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ScanAppPackage) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *ScanAppPackage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ScanAppPackage) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type ScanAppRequest struct {
	Packages []*ScanAppPackage `protobuf:"bytes,1,rep,name=Packages" json:"Packages,omitempty"`
}

func (m *ScanAppRequest) Reset()                    { *m = ScanAppRequest{} }
func (m *ScanAppRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanAppRequest) ProtoMessage()               {}
func (*ScanAppRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

func (m *ScanAppRequest) GetPackages() []*ScanAppPackage {
	if m != nil {
		return m.Packages
	}
	return nil
}

type ScanAwsLambdaRequest struct {
	ResType     string `protobuf:"bytes,1,opt,name=ResType" json:"ResType,omitempty"`
	FuncName    string `protobuf:"bytes,2,opt,name=FuncName" json:"FuncName,omitempty"`
	Region      string `protobuf:"bytes,3,opt,name=Region" json:"Region,omitempty"`
	FuncLink    string `protobuf:"bytes,4,opt,name=FuncLink" json:"FuncLink,omitempty"`
	ScanSecrets bool   `protobuf:"varint,5,opt,name=ScanSecrets" json:"ScanSecrets,omitempty"`
}

func (m *ScanAwsLambdaRequest) Reset()                    { *m = ScanAwsLambdaRequest{} }
func (m *ScanAwsLambdaRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanAwsLambdaRequest) ProtoMessage()               {}
func (*ScanAwsLambdaRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *ScanAwsLambdaRequest) GetResType() string {
	if m != nil {
		return m.ResType
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetFuncLink() string {
	if m != nil {
		return m.FuncLink
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetScanSecrets() bool {
	if m != nil {
		return m.ScanSecrets
	}
	return false
}

type ScannerSettings struct {
	EnableTLSVerification bool   `protobuf:"varint,1,opt,name=EnableTLSVerification" json:"EnableTLSVerification,omitempty"`
	CACerts               string `protobuf:"bytes,2,opt,name=CACerts" json:"CACerts,omitempty"`
	HttpProxy             string `protobuf:"bytes,3,opt,name=httpProxy" json:"httpProxy,omitempty"`
	HttpsProxy            string `protobuf:"bytes,4,opt,name=httpsProxy" json:"httpsProxy,omitempty"`
	NoProxy               string `protobuf:"bytes,5,opt,name=noProxy" json:"noProxy,omitempty"`
}

func (m *ScannerSettings) Reset()                    { *m = ScannerSettings{} }
func (m *ScannerSettings) String() string            { return proto.CompactTextString(m) }
func (*ScannerSettings) ProtoMessage()               {}
func (*ScannerSettings) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

func (m *ScannerSettings) GetEnableTLSVerification() bool {
	if m != nil {
		return m.EnableTLSVerification
	}
	return false
}

func (m *ScannerSettings) GetCACerts() string {
	if m != nil {
		return m.CACerts
	}
	return ""
}

func (m *ScannerSettings) GetHttpProxy() string {
	if m != nil {
		return m.HttpProxy
	}
	return ""
}

func (m *ScannerSettings) GetHttpsProxy() string {
	if m != nil {
		return m.HttpsProxy
	}
	return ""
}

func (m *ScannerSettings) GetNoProxy() string {
	if m != nil {
		return m.NoProxy
	}
	return ""
}

type TrivyScanResponse struct {
	Results []*TrivyScanResponse_Result `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
}

func (m *TrivyScanResponse) Reset()                    { *m = TrivyScanResponse{} }
func (m *TrivyScanResponse) String() string            { return proto.CompactTextString(m) }
func (*TrivyScanResponse) ProtoMessage()               {}
func (*TrivyScanResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *TrivyScanResponse) GetResults() []*TrivyScanResponse_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type TrivyScanResponse_Vulnerability struct {
	VulnerabilityID  string             `protobuf:"bytes,1,opt,name=VulnerabilityID" json:"VulnerabilityID,omitempty"`
	PkgName          string             `protobuf:"bytes,2,opt,name=PkgName" json:"PkgName,omitempty"`
	PkgID            string             `protobuf:"bytes,3,opt,name=PkgID" json:"PkgID,omitempty"`
	PkgIdentifier    *PackageIdentifier `protobuf:"bytes,4,opt,name=PkgIdentifier" json:"PkgIdentifier,omitempty"`
	InstalledVersion string             `protobuf:"bytes,5,opt,name=InstalledVersion" json:"InstalledVersion,omitempty"`
	FixedVersion     string             `protobuf:"bytes,6,opt,name=FixedVersion" json:"FixedVersion,omitempty"`
	Status           string             `protobuf:"bytes,7,opt,name=Status" json:"Status,omitempty"`
	Layer            *Layer             `protobuf:"bytes,8,opt,name=Layer" json:"Layer,omitempty"`
	SeveritySource   string             `protobuf:"bytes,9,opt,name=SeveritySource" json:"SeveritySource,omitempty"`
	PrimaryURL       string             `protobuf:"bytes,10,opt,name=PrimaryURL" json:"PrimaryURL,omitempty"`
	DataSource       *DataSource        `protobuf:"bytes,11,opt,name=DataSource" json:"DataSource,omitempty"`
	Title            string             `protobuf:"bytes,12,opt,name=Title" json:"Title,omitempty"`
	Description      string             `protobuf:"bytes,13,opt,name=Description" json:"Description,omitempty"`
	Severity         string             `protobuf:"bytes,14,opt,name=Severity" json:"Severity,omitempty"`
	VendorSeverity   map[string]int32   `protobuf:"bytes,15,rep,name=VendorSeverity" json:"VendorSeverity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CVSS             map[string]*CVSS   `protobuf:"bytes,16,rep,name=CVSS" json:"CVSS,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	References       []string           `protobuf:"bytes,17,rep,name=References" json:"References,omitempty"`
	PublishedDate    string             `protobuf:"bytes,18,opt,name=PublishedDate" json:"PublishedDate,omitempty"`
	LastModifiedDate string             `protobuf:"bytes,19,opt,name=LastModifiedDate" json:"LastModifiedDate,omitempty"`
}

func (m *TrivyScanResponse_Vulnerability) Reset()         { *m = TrivyScanResponse_Vulnerability{} }
func (m *TrivyScanResponse_Vulnerability) String() string { return proto.CompactTextString(m) }
func (*TrivyScanResponse_Vulnerability) ProtoMessage()    {}
func (*TrivyScanResponse_Vulnerability) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{18, 0}
}

func (m *TrivyScanResponse_Vulnerability) GetVulnerabilityID() string {
	if m != nil {
		return m.VulnerabilityID
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetPkgID() string {
	if m != nil {
		return m.PkgID
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetPkgIdentifier() *PackageIdentifier {
	if m != nil {
		return m.PkgIdentifier
	}
	return nil
}

func (m *TrivyScanResponse_Vulnerability) GetInstalledVersion() string {
	if m != nil {
		return m.InstalledVersion
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetFixedVersion() string {
	if m != nil {
		return m.FixedVersion
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetLayer() *Layer {
	if m != nil {
		return m.Layer
	}
	return nil
}

func (m *TrivyScanResponse_Vulnerability) GetSeveritySource() string {
	if m != nil {
		return m.SeveritySource
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetPrimaryURL() string {
	if m != nil {
		return m.PrimaryURL
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetDataSource() *DataSource {
	if m != nil {
		return m.DataSource
	}
	return nil
}

func (m *TrivyScanResponse_Vulnerability) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetVendorSeverity() map[string]int32 {
	if m != nil {
		return m.VendorSeverity
	}
	return nil
}

func (m *TrivyScanResponse_Vulnerability) GetCVSS() map[string]*CVSS {
	if m != nil {
		return m.CVSS
	}
	return nil
}

func (m *TrivyScanResponse_Vulnerability) GetReferences() []string {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *TrivyScanResponse_Vulnerability) GetPublishedDate() string {
	if m != nil {
		return m.PublishedDate
	}
	return ""
}

func (m *TrivyScanResponse_Vulnerability) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

type TrivyScanResponse_Result struct {
	Vulnerabilities []*TrivyScanResponse_Vulnerability `protobuf:"bytes,1,rep,name=Vulnerabilities" json:"Vulnerabilities,omitempty"`
}

func (m *TrivyScanResponse_Result) Reset()                    { *m = TrivyScanResponse_Result{} }
func (m *TrivyScanResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*TrivyScanResponse_Result) ProtoMessage()               {}
func (*TrivyScanResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18, 1} }

func (m *TrivyScanResponse_Result) GetVulnerabilities() []*TrivyScanResponse_Vulnerability {
	if m != nil {
		return m.Vulnerabilities
	}
	return nil
}

type PackageIdentifier struct {
	PURL string `protobuf:"bytes,1,opt,name=PURL" json:"PURL,omitempty"`
	UID  string `protobuf:"bytes,2,opt,name=UID" json:"UID,omitempty"`
}

func (m *PackageIdentifier) Reset()                    { *m = PackageIdentifier{} }
func (m *PackageIdentifier) String() string            { return proto.CompactTextString(m) }
func (*PackageIdentifier) ProtoMessage()               {}
func (*PackageIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

func (m *PackageIdentifier) GetPURL() string {
	if m != nil {
		return m.PURL
	}
	return ""
}

func (m *PackageIdentifier) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type Layer struct {
	Digest string `protobuf:"bytes,1,opt,name=Digest" json:"Digest,omitempty"`
	DiffID string `protobuf:"bytes,2,opt,name=DiffID" json:"DiffID,omitempty"`
}

func (m *Layer) Reset()                    { *m = Layer{} }
func (m *Layer) String() string            { return proto.CompactTextString(m) }
func (*Layer) ProtoMessage()               {}
func (*Layer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

func (m *Layer) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Layer) GetDiffID() string {
	if m != nil {
		return m.DiffID
	}
	return ""
}

type DataSource struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	URL  string `protobuf:"bytes,3,opt,name=URL" json:"URL,omitempty"`
}

func (m *DataSource) Reset()                    { *m = DataSource{} }
func (m *DataSource) String() string            { return proto.CompactTextString(m) }
func (*DataSource) ProtoMessage()               {}
func (*DataSource) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func (m *DataSource) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DataSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataSource) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type CVSS struct {
	V3Vector string  `protobuf:"bytes,1,opt,name=V3Vector" json:"V3Vector,omitempty"`
	V3Score  float32 `protobuf:"fixed32,2,opt,name=V3Score" json:"V3Score,omitempty"`
	V2Vector string  `protobuf:"bytes,3,opt,name=V2Vector" json:"V2Vector,omitempty"`
	V2Score  float32 `protobuf:"fixed32,4,opt,name=V2Score" json:"V2Score,omitempty"`
}

func (m *CVSS) Reset()                    { *m = CVSS{} }
func (m *CVSS) String() string            { return proto.CompactTextString(m) }
func (*CVSS) ProtoMessage()               {}
func (*CVSS) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{22} }

func (m *CVSS) GetV3Vector() string {
	if m != nil {
		return m.V3Vector
	}
	return ""
}

func (m *CVSS) GetV3Score() float32 {
	if m != nil {
		return m.V3Score
	}
	return 0
}

func (m *CVSS) GetV2Vector() string {
	if m != nil {
		return m.V2Vector
	}
	return ""
}

func (m *CVSS) GetV2Score() float32 {
	if m != nil {
		return m.V2Score
	}
	return 0
}

func init() {
	proto.RegisterType((*ScanTypeMap)(nil), "share.ScanTypeMap")
	proto.RegisterType((*ScanVulnerability)(nil), "share.ScanVulnerability")
	proto.RegisterType((*ScanLayerResult)(nil), "share.ScanLayerResult")
	proto.RegisterType((*ScanModule)(nil), "share.ScanModule")
	proto.RegisterType((*ScanModuleVul)(nil), "share.ScanModuleVul")
	proto.RegisterType((*ScanSecretLog)(nil), "share.ScanSecretLog")
	proto.RegisterType((*ScanSecretResult)(nil), "share.ScanSecretResult")
	proto.RegisterType((*ScanSetIdPermLog)(nil), "share.ScanSetIdPermLog")
	proto.RegisterType((*ScanResult)(nil), "share.ScanResult")
	proto.RegisterType((*SBOMMetadata)(nil), "share.SBOMMetadata")
	proto.RegisterType((*ScanSignatureInfo)(nil), "share.ScanSignatureInfo")
	proto.RegisterType((*ScanRunningRequest)(nil), "share.ScanRunningRequest")
	proto.RegisterType((*ScanData)(nil), "share.ScanData")
	proto.RegisterType((*WorkloadMetadata)(nil), "share.WorkloadMetadata")
	proto.RegisterType((*ScanAppPackage)(nil), "share.ScanAppPackage")
	proto.RegisterType((*ScanAppRequest)(nil), "share.ScanAppRequest")
	proto.RegisterType((*ScanAwsLambdaRequest)(nil), "share.ScanAwsLambdaRequest")
	proto.RegisterType((*ScannerSettings)(nil), "share.ScannerSettings")
	proto.RegisterType((*TrivyScanResponse)(nil), "share.TrivyScanResponse")
	proto.RegisterType((*TrivyScanResponse_Vulnerability)(nil), "share.TrivyScanResponse.Vulnerability")
	proto.RegisterType((*TrivyScanResponse_Result)(nil), "share.TrivyScanResponse.Result")
	proto.RegisterType((*PackageIdentifier)(nil), "share.PackageIdentifier")
	proto.RegisterType((*Layer)(nil), "share.Layer")
	proto.RegisterType((*DataSource)(nil), "share.DataSource")
	proto.RegisterType((*CVSS)(nil), "share.CVSS")
	proto.RegisterEnum("share.ScanErrorCode", ScanErrorCode_name, ScanErrorCode_value)
	proto.RegisterEnum("share.ScanObjectType", ScanObjectType_name, ScanObjectType_value)
	proto.RegisterEnum("share.ScanProvider", ScanProvider_name, ScanProvider_value)
	proto.RegisterEnum("share.ScanVulStatus", ScanVulStatus_name, ScanVulStatus_value)
}

func init() { proto.RegisterFile("scan.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 2316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x18, 0x5d, 0x73, 0x23, 0x39,
	0xf1, 0xfc, 0x91, 0xc4, 0x91, 0x9d, 0x64, 0xa2, 0x64, 0xb3, 0xb3, 0xe1, 0xee, 0x08, 0x53, 0xd4,
	0xd5, 0x12, 0xb6, 0x02, 0x9b, 0x85, 0x5a, 0xf6, 0xa8, 0xa2, 0x2a, 0x89, 0x27, 0x9c, 0xc1, 0x49,
	0x7c, 0x72, 0xd6, 0x47, 0xf1, 0x36, 0xf1, 0x28, 0xce, 0x90, 0xf1, 0x8c, 0x91, 0x34, 0xd9, 0x98,
	0xa7, 0x7b, 0xe3, 0x17, 0xc0, 0x0f, 0xa0, 0x28, 0xaa, 0x28, 0xde, 0x78, 0xe3, 0x8f, 0xf0, 0x0b,
	0x78, 0xe1, 0x5f, 0x50, 0xdd, 0xd2, 0x8c, 0x35, 0xb6, 0xf7, 0x6e, 0x79, 0x53, 0x7f, 0xa8, 0xd5,
	0xad, 0x6e, 0xf5, 0x87, 0x08, 0x91, 0xc3, 0x20, 0x39, 0x9a, 0x88, 0x54, 0xa5, 0x74, 0x45, 0xde,
	0x05, 0x82, 0x7b, 0x5f, 0x92, 0x66, 0x7f, 0x18, 0x24, 0xd7, 0xd3, 0x09, 0xbf, 0x08, 0x26, 0xf4,
	0xfb, 0x64, 0x63, 0x90, 0xc5, 0x09, 0x17, 0xc1, 0x4d, 0x14, 0x47, 0x6a, 0xea, 0x56, 0x0e, 0x2a,
	0xcf, 0x1b, 0xac, 0x8c, 0xa4, 0x1f, 0x93, 0xf5, 0x7e, 0x34, 0x4a, 0x02, 0x95, 0x09, 0xee, 0x56,
	0x91, 0x63, 0x86, 0xf0, 0xfe, 0x5b, 0x27, 0xdb, 0x20, 0xb3, 0xbc, 0x87, 0x92, 0xfa, 0x65, 0x30,
	0xe6, 0x28, 0x70, 0x9d, 0xe1, 0x9a, 0xee, 0x92, 0x95, 0xfe, 0x30, 0x35, 0x32, 0xaa, 0x4c, 0x03,
	0x74, 0x9f, 0x34, 0xfa, 0xfc, 0x81, 0x0b, 0x38, 0xbe, 0x86, 0xdc, 0x05, 0x4c, 0x0f, 0x48, 0xb3,
	0xcd, 0xe5, 0x50, 0x44, 0x13, 0x15, 0xa5, 0x89, 0x5b, 0x47, 0xb2, 0x8d, 0xa2, 0x3f, 0x21, 0x4f,
	0x7a, 0xc1, 0xf0, 0x3e, 0x18, 0x71, 0x38, 0xa2, 0xcd, 0x27, 0x82, 0x0f, 0x03, 0xc5, 0x43, 0x77,
	0x05, 0x79, 0x97, 0x13, 0xe9, 0x67, 0x64, 0xd3, 0x10, 0x06, 0x5c, 0x48, 0x10, 0xbd, 0x8a, 0xec,
	0x73, 0x58, 0xea, 0x91, 0xd6, 0x79, 0xf4, 0xc8, 0xc3, 0x9c, 0x6b, 0x0d, 0xb9, 0x4a, 0x38, 0xb0,
	0xb4, 0x1b, 0x25, 0xf7, 0x6e, 0x43, 0x5b, 0x0a, 0x6b, 0xea, 0x92, 0xb5, 0x01, 0x1f, 0xaa, 0x54,
	0x48, 0x77, 0x1d, 0xd1, 0x39, 0x08, 0x14, 0x34, 0x7b, 0xf0, 0xca, 0x25, 0x78, 0x0b, 0x39, 0x08,
	0xb7, 0x6c, 0x98, 0x06, 0xaf, 0xdc, 0x26, 0xee, 0x9a, 0x21, 0xc0, 0x53, 0xbd, 0xec, 0x26, 0x8e,
	0xe4, 0x1d, 0x0f, 0xdb, 0x81, 0xe2, 0x6e, 0x0b, 0x39, 0xca, 0x48, 0x7a, 0x48, 0x9c, 0x6e, 0x20,
	0xd5, 0x45, 0x1a, 0x46, 0xb7, 0x91, 0x61, 0xdc, 0x40, 0xc6, 0x05, 0x3c, 0xe8, 0x7d, 0xd6, 0xf3,
	0xa5, 0xbb, 0x79, 0x50, 0x03, 0xbd, 0x61, 0x8d, 0xb8, 0x81, 0x2f, 0xdd, 0x2d, 0x83, 0x1b, 0xf8,
	0x92, 0x7e, 0x4a, 0xc8, 0x39, 0xe7, 0x21, 0x0b, 0x54, 0x94, 0x8c, 0x5c, 0x07, 0xa5, 0x59, 0x18,
	0xba, 0x47, 0x56, 0x3b, 0xc9, 0x69, 0x20, 0xb9, 0xbb, 0x8d, 0xa1, 0x61, 0x20, 0xf0, 0x76, 0xfb,
	0xf4, 0xd7, 0x7c, 0xea, 0x52, 0xdc, 0xa2, 0x01, 0xf0, 0xf6, 0x79, 0x14, 0xa3, 0x3f, 0xdc, 0x1d,
	0xed, 0xed, 0x1c, 0x06, 0x6f, 0x5b, 0xee, 0x72, 0x77, 0xb5, 0xb7, 0x2d, 0x94, 0xf7, 0xcf, 0x0a,
	0xd9, 0x82, 0x58, 0xeb, 0x06, 0x53, 0x2e, 0x18, 0x97, 0x59, 0xac, 0xe0, 0xfc, 0x76, 0x34, 0xe2,
	0x52, 0x99, 0x58, 0x33, 0x10, 0x7d, 0x41, 0xea, 0x83, 0x2c, 0x96, 0x6e, 0xf5, 0xa0, 0xf6, 0xbc,
	0x79, 0xec, 0x1e, 0xe1, 0x03, 0x38, 0x5a, 0x88, 0x54, 0x86, 0x5c, 0x68, 0xf9, 0x38, 0x94, 0x26,
	0x02, 0x71, 0x0d, 0xb8, 0x7e, 0xf4, 0x07, 0x8e, 0x61, 0x57, 0x63, 0xb8, 0xa6, 0x2f, 0xc9, 0x5a,
	0x9f, 0x0f, 0x05, 0x57, 0x12, 0x23, 0xac, 0x79, 0xfc, 0xd4, 0x12, 0xac, 0x29, 0x5a, 0x2f, 0x96,
	0xf3, 0x79, 0x7f, 0xad, 0x10, 0x02, 0xd4, 0x8b, 0x34, 0xcc, 0x62, 0xbe, 0xf4, 0x65, 0x60, 0xbc,
	0xe8, 0x10, 0xab, 0xe6, 0xf1, 0xa2, 0xa3, 0x6b, 0x8f, 0xac, 0xf6, 0xd3, 0x4c, 0x0c, 0xb9, 0xd1,
	0xcc, 0x40, 0xf4, 0xb9, 0xb1, 0xae, 0x8e, 0xd6, 0xed, 0x5a, 0x4a, 0xe8, 0x63, 0x06, 0x59, 0x6c,
	0x59, 0x06, 0x7e, 0x5e, 0x29, 0xfb, 0x19, 0x6e, 0xdd, 0x44, 0x3d, 0xae, 0xbd, 0x2f, 0xc9, 0x46,
	0x69, 0xfb, 0x52, 0x45, 0x5f, 0x90, 0xd5, 0xbe, 0x0a, 0x54, 0x26, 0x51, 0xcf, 0xcd, 0xd2, 0xc1,
	0x83, 0x2c, 0xd6, 0x34, 0x66, 0x78, 0xbc, 0x3f, 0x56, 0xb4, 0x4c, 0x7d, 0x13, 0xdd, 0x74, 0x04,
	0x32, 0x21, 0xf7, 0xe4, 0x32, 0x61, 0x8d, 0x38, 0xfe, 0xa8, 0x8c, 0xe5, 0xb8, 0x2e, 0x14, 0xac,
	0xcd, 0x14, 0x84, 0xd0, 0x61, 0x59, 0xcc, 0xe1, 0xf5, 0x9b, 0x4c, 0x50, 0xc0, 0x10, 0xa4, 0xfd,
	0x6c, 0x04, 0x7e, 0x87, 0x3b, 0xd4, 0x6f, 0xdf, 0xc2, 0x78, 0x77, 0xc4, 0x99, 0x77, 0x10, 0x3d,
	0x24, 0x2b, 0xbe, 0x10, 0xa9, 0x40, 0x65, 0xca, 0xa6, 0x20, 0xfe, 0x2c, 0x0d, 0x39, 0xd3, 0x2c,
	0x70, 0xdd, 0xdd, 0x74, 0x94, 0x07, 0xd3, 0xee, 0x82, 0xcf, 0xbb, 0xe9, 0x88, 0x21, 0x87, 0x37,
	0xc8, 0x4f, 0x52, 0x9d, 0xb0, 0xc7, 0xc5, 0xf8, 0x1b, 0xac, 0x46, 0x0b, 0xab, 0x65, 0x0b, 0xfd,
	0x87, 0x28, 0xe4, 0x49, 0xe1, 0xee, 0x02, 0xf6, 0xfe, 0xd6, 0xd0, 0x51, 0x64, 0x94, 0xb7, 0x22,
	0xa6, 0x52, 0x8e, 0x98, 0xc2, 0xac, 0xea, 0xb7, 0x9b, 0xf5, 0x31, 0x59, 0x07, 0xb7, 0xca, 0x49,
	0x50, 0x9c, 0x38, 0x43, 0x14, 0x2f, 0xa8, 0xfe, 0x41, 0x2f, 0xe8, 0x80, 0x34, 0xcf, 0xd2, 0x44,
	0x05, 0x51, 0xc2, 0x45, 0xa7, 0x6d, 0x7c, 0x60, 0xa3, 0x20, 0x96, 0xbf, 0x48, 0xa5, 0xea, 0xb4,
	0x4d, 0xdc, 0x19, 0x08, 0x1d, 0xcb, 0x47, 0x91, 0x54, 0x62, 0x6a, 0x32, 0x6c, 0x01, 0x83, 0x63,
	0x19, 0x9f, 0xa4, 0x32, 0x52, 0xa9, 0x98, 0x9a, 0x1c, 0x6b, 0x61, 0xa8, 0x43, 0x6a, 0xd7, 0xc1,
	0xc8, 0x64, 0x59, 0x58, 0x5a, 0xf9, 0x80, 0x94, 0xf2, 0x81, 0x4b, 0xd6, 0x3a, 0xe3, 0x60, 0xc4,
	0x3b, 0x6d, 0x93, 0x5d, 0x73, 0x90, 0x1e, 0x91, 0x55, 0x4c, 0x28, 0xd2, 0x6d, 0xa1, 0xa5, 0x7b,
	0x96, 0xa5, 0x56, 0xa6, 0x61, 0x86, 0x0b, 0x5c, 0xe7, 0x27, 0x0f, 0xd2, 0xdd, 0xd0, 0x2f, 0x0a,
	0xd6, 0xf4, 0xa7, 0x20, 0xe3, 0x86, 0xc7, 0x3a, 0x9f, 0x36, 0x8f, 0x3f, 0xb1, 0x64, 0xe8, 0xed,
	0x47, 0x9a, 0xee, 0x27, 0x4a, 0x4c, 0x99, 0x61, 0x06, 0xd3, 0x7b, 0x71, 0xa0, 0x6e, 0x53, 0x31,
	0x76, 0xb7, 0xb4, 0xe9, 0x39, 0x4c, 0x9f, 0x93, 0xad, 0x7c, 0x9d, 0xbb, 0x5a, 0x67, 0xdf, 0x79,
	0x34, 0x98, 0x7c, 0x92, 0xa9, 0xbb, 0x54, 0x60, 0x0a, 0x5e, 0x67, 0x06, 0x02, 0x09, 0x67, 0x03,
	0xbf, 0x7d, 0x7a, 0x26, 0x78, 0xa0, 0xf8, 0x75, 0x34, 0xe6, 0x26, 0x19, 0xcf, 0xa3, 0xe9, 0x0f,
	0xc9, 0x9a, 0x7e, 0xf8, 0xd2, 0xdd, 0x41, 0xfd, 0xb7, 0x17, 0x32, 0x0a, 0xcb, 0x39, 0xec, 0x1c,
	0xb8, 0xfb, 0x61, 0x39, 0xb0, 0x48, 0xaf, 0x4f, 0x4c, 0x12, 0x82, 0xf4, 0xfa, 0x9a, 0x90, 0xe2,
	0x95, 0x48, 0x77, 0x0f, 0x8f, 0x2d, 0x4b, 0x9a, 0x3d, 0x21, 0x66, 0xb1, 0xd2, 0x1f, 0x91, 0x46,
	0x4f, 0xa4, 0xf0, 0x30, 0x84, 0xfb, 0x14, 0x83, 0x7c, 0xc7, 0xda, 0x96, 0x93, 0x58, 0xc1, 0x54,
	0x24, 0x72, 0xd7, 0x4a, 0xe4, 0xbf, 0x20, 0x1b, 0x45, 0x0f, 0xd3, 0x49, 0x6e, 0x53, 0xf7, 0x19,
	0x9a, 0x62, 0x47, 0x79, 0x89, 0xce, 0xca, 0xec, 0x10, 0x4e, 0xfa, 0xfe, 0x42, 0x77, 0x5f, 0x87,
	0x93, 0x01, 0xe9, 0x29, 0xa1, 0x79, 0x8f, 0x25, 0x19, 0xff, 0x7d, 0xc6, 0x25, 0x30, 0x7d, 0x07,
	0xc5, 0x53, 0x4b, 0xbc, 0x69, 0xc2, 0xd8, 0x12, 0xee, 0xfd, 0x37, 0xa4, 0x69, 0x85, 0x0b, 0x44,
	0xf9, 0x3d, 0x9f, 0x9a, 0x97, 0x0e, 0x4b, 0xa8, 0xae, 0x0f, 0x41, 0x9c, 0xe5, 0xf9, 0x43, 0x03,
	0x9f, 0x57, 0x7f, 0x56, 0xf1, 0xfe, 0x5c, 0x21, 0xad, 0xfe, 0xe9, 0xd5, 0xc5, 0x05, 0x57, 0x41,
	0x18, 0xa8, 0x00, 0x5a, 0x07, 0x96, 0xa6, 0xaa, 0x1d, 0x09, 0xec, 0x26, 0x72, 0x31, 0x65, 0x24,
	0xa4, 0x02, 0xc8, 0x41, 0xbd, 0x40, 0xdd, 0xe9, 0x34, 0xb7, 0xce, 0x66, 0x08, 0x7a, 0x4a, 0xb6,
	0xae, 0x45, 0xf4, 0x30, 0x9d, 0x85, 0xb3, 0x5b, 0x2b, 0x65, 0x05, 0x9b, 0x3a, 0x49, 0x13, 0xc9,
	0xd9, 0xfc, 0x06, 0xef, 0x1f, 0x15, 0xdd, 0x28, 0x96, 0xef, 0x11, 0xdb, 0x1e, 0x01, 0x6d, 0x89,
	0x90, 0x6e, 0x45, 0x9f, 0x5b, 0x20, 0xa0, 0xbd, 0xd3, 0xc0, 0x30, 0x80, 0x3c, 0x0e, 0xb1, 0x2a,
	0x55, 0x30, 0x9e, 0x18, 0xb3, 0x97, 0x13, 0xe9, 0x29, 0xd9, 0xb6, 0x09, 0x3a, 0x1d, 0xd6, 0xbe,
	0x21, 0x1d, 0x2e, 0xb2, 0x7b, 0x7f, 0xaa, 0x68, 0x37, 0xb2, 0x2c, 0x49, 0xa2, 0x64, 0x64, 0x5c,
	0x43, 0x7f, 0x60, 0xa5, 0xf2, 0xcd, 0xe3, 0x27, 0x96, 0xb4, 0xab, 0x9b, 0xdf, 0xf1, 0xa1, 0x02,
	0xa2, 0xc9, 0xf0, 0x9b, 0xa4, 0xda, 0x69, 0x1b, 0x45, 0xab, 0x9d, 0x36, 0x44, 0xcc, 0xc9, 0x88,
	0x27, 0x90, 0xff, 0x74, 0xaa, 0xcd, 0x41, 0x68, 0xdb, 0x70, 0xc9, 0x7a, 0x67, 0x7e, 0x12, 0xf6,
	0xd2, 0x28, 0x51, 0xa6, 0xc2, 0x2d, 0xe0, 0xbd, 0xff, 0x54, 0x48, 0x03, 0x8e, 0x6b, 0x83, 0x6b,
	0xff, 0x9f, 0x12, 0xb6, 0x47, 0x56, 0x4f, 0xb3, 0xdb, 0x5b, 0xae, 0x0b, 0x43, 0x8b, 0x19, 0x88,
	0xbe, 0x26, 0xad, 0xfe, 0x4d, 0x3a, 0xce, 0xc3, 0x05, 0x75, 0x6b, 0xce, 0x5e, 0x94, 0x15, 0x49,
	0xac, 0xc4, 0x88, 0x35, 0xf7, 0xf4, 0xea, 0xc2, 0x08, 0xad, 0xa3, 0x50, 0x0b, 0x43, 0x7f, 0x4e,
	0x5a, 0x5f, 0xa5, 0xe2, 0x3e, 0x4e, 0x83, 0x10, 0xf6, 0xcc, 0xf5, 0x4b, 0x36, 0x49, 0x0b, 0xb7,
	0x31, 0x5e, 0x9b, 0x38, 0xf3, 0x1c, 0x4b, 0x1b, 0x92, 0x52, 0x05, 0xab, 0xce, 0x55, 0x30, 0xef,
	0xeb, 0x0a, 0xd9, 0x84, 0xcb, 0x38, 0x99, 0x4c, 0x4c, 0x1b, 0x89, 0x5e, 0x98, 0x4c, 0x2c, 0x39,
	0x39, 0x08, 0xf6, 0xe8, 0x0c, 0x87, 0x44, 0x2d, 0xcb, 0xc2, 0xd8, 0x25, 0xb7, 0x56, 0x2e, 0xb9,
	0x76, 0x53, 0x5b, 0x2f, 0x37, 0xb5, 0xde, 0x59, 0xa1, 0x41, 0x1e, 0x42, 0x2f, 0x49, 0xc3, 0x28,
	0xa3, 0x03, 0xbe, 0x59, 0x0a, 0xa3, 0x99, 0xaa, 0xac, 0x60, 0xf3, 0xfe, 0x52, 0x21, 0xbb, 0x48,
	0x7c, 0x27, 0xbb, 0xc1, 0xf8, 0x26, 0x0c, 0x72, 0x59, 0x2e, 0x59, 0x63, 0x5c, 0x5a, 0xcd, 0x45,
	0x0e, 0xa2, 0x4e, 0x59, 0x32, 0xb4, 0x6c, 0x29, 0x60, 0x08, 0x05, 0x28, 0xb0, 0x85, 0x21, 0x06,
	0xca, 0xf7, 0xe0, 0x38, 0x53, 0x9f, 0xed, 0xc1, 0x91, 0xe6, 0x40, 0x4f, 0x8e, 0x76, 0xf3, 0xdb,
	0x60, 0x36, 0xca, 0xfb, 0x97, 0x69, 0xce, 0x13, 0x2e, 0xfa, 0x5c, 0xc1, 0x6c, 0x80, 0xef, 0xd7,
	0x4f, 0x82, 0x9b, 0x98, 0x5f, 0x77, 0xfb, 0xf6, 0x1b, 0x33, 0x83, 0xe6, 0x72, 0x22, 0xe6, 0xd6,
	0x93, 0x33, 0x2e, 0x94, 0xcc, 0xdb, 0x61, 0x03, 0x82, 0xbb, 0xef, 0x94, 0x9a, 0xf4, 0x44, 0xfa,
	0x98, 0x4f, 0x8b, 0x33, 0x04, 0x78, 0x10, 0x00, 0xa9, 0xc9, 0xda, 0x02, 0x0b, 0x03, 0x72, 0x93,
	0x54, 0x13, 0x75, 0x7b, 0x92, 0x83, 0xde, 0xbf, 0x1b, 0x64, 0x7b, 0x21, 0x85, 0xd1, 0x37, 0x78,
	0xbb, 0x59, 0xac, 0x72, 0x47, 0x7d, 0xf7, 0x7d, 0xd9, 0xee, 0x28, 0x2f, 0x78, 0x86, 0x7f, 0xff,
	0xef, 0x6b, 0x73, 0xa3, 0x35, 0x14, 0xe3, 0x12, 0xa2, 0xd3, 0x36, 0x2e, 0x9b, 0x47, 0x83, 0x9a,
	0xbd, 0xfb, 0x91, 0xe5, 0xb9, 0x1c, 0x84, 0xac, 0xdf, 0xbb, 0x1f, 0x15, 0x09, 0x44, 0x03, 0x50,
	0xca, 0x60, 0x11, 0xf2, 0x44, 0x61, 0xda, 0x44, 0xcb, 0x67, 0xa9, 0xd9, 0x44, 0xd1, 0x8c, 0xce,
	0xca, 0xec, 0x90, 0x7e, 0x3a, 0x89, 0x54, 0x41, 0x1c, 0xcf, 0x26, 0x5d, 0x7d, 0x3f, 0x0b, 0xf8,
	0x85, 0x89, 0x78, 0x75, 0xc9, 0x44, 0xbc, 0x57, 0x0c, 0x09, 0x6b, 0x66, 0x66, 0x41, 0x88, 0x7a,
	0x64, 0x05, 0x3b, 0x28, 0x6c, 0xe3, 0x9a, 0xc7, 0x2d, 0xa3, 0x9f, 0x6e, 0xb1, 0x34, 0x09, 0x26,
	0xf3, 0x7c, 0xfa, 0x37, 0x73, 0x8f, 0x6e, 0xed, 0xe6, 0xb0, 0xe0, 0xea, 0x9e, 0x88, 0xc6, 0x81,
	0x98, 0xbe, 0x65, 0x5d, 0xd3, 0xe9, 0x59, 0x18, 0xfa, 0x92, 0x10, 0xc8, 0x90, 0x46, 0x46, 0x13,
	0x0f, 0xcc, 0x7b, 0x9a, 0x19, 0x81, 0x59, 0x4c, 0x70, 0xb9, 0xd7, 0x91, 0x8a, 0xf3, 0xd1, 0x5a,
	0x03, 0xf3, 0x5f, 0x10, 0x1b, 0x8b, 0x5f, 0x10, 0xf6, 0x07, 0xc6, 0xe6, 0xdc, 0x07, 0xc6, 0x0d,
	0xd9, 0x1c, 0xf0, 0x24, 0x4c, 0x45, 0xc1, 0xb1, 0x85, 0x81, 0xf4, 0xf9, 0x7b, 0x03, 0xa9, 0x14,
	0x0c, 0x47, 0xe5, 0xcd, 0xba, 0x77, 0x9c, 0x93, 0x48, 0xdb, 0x30, 0xb4, 0xf7, 0xfb, 0xae, 0x83,
	0x92, 0x7f, 0xfc, 0x81, 0x92, 0x61, 0x8b, 0x96, 0x87, 0xbb, 0x75, 0xa3, 0x7d, 0xcb, 0x05, 0x0c,
	0x1b, 0xd2, 0xdd, 0xc6, 0x42, 0x6c, 0x61, 0x16, 0x3f, 0x20, 0xe8, 0x87, 0x7e, 0x40, 0xec, 0x2c,
	0xff, 0x80, 0xd8, 0x3f, 0x21, 0x3b, 0x4b, 0xcc, 0xfb, 0xb6, 0x5e, 0x67, 0xc5, 0xea, 0x75, 0xf6,
	0xdb, 0x64, 0xbd, 0xb0, 0x63, 0xc9, 0xc6, 0xef, 0xd9, 0x1b, 0x9b, 0xc7, 0x4d, 0x73, 0x35, 0xb0,
	0xc5, 0x96, 0xf2, 0x5b, 0x48, 0x87, 0x38, 0x55, 0xf5, 0xca, 0x6f, 0x34, 0x2a, 0x32, 0xf4, 0x67,
	0x1f, 0x76, 0xab, 0x6c, 0x7e, 0xbb, 0xf7, 0x86, 0x6c, 0x2f, 0xbc, 0x3f, 0x28, 0x64, 0x3d, 0x08,
	0x5b, 0x53, 0xc8, 0x60, 0x0d, 0xda, 0xbf, 0x2d, 0xda, 0x05, 0x58, 0x7a, 0xaf, 0xcd, 0x73, 0x79,
	0xef, 0x0f, 0x07, 0xe2, 0x6f, 0x6f, 0x8b, 0x5d, 0x06, 0xf2, 0x4e, 0xed, 0xd8, 0x37, 0x6d, 0x48,
	0xa5, 0x68, 0x43, 0xf2, 0x2a, 0x5a, 0xb5, 0xaa, 0x28, 0x1c, 0xce, 0xba, 0x26, 0xab, 0xc0, 0xd2,
	0x13, 0x3a, 0xa8, 0x20, 0xb8, 0x07, 0xaf, 0xf4, 0x37, 0x94, 0x91, 0x51, 0xc0, 0x58, 0x10, 0x5f,
	0xd9, 0x3f, 0x7a, 0x39, 0x88, 0xbb, 0x8e, 0xcd, 0x2e, 0x33, 0xc8, 0xe6, 0x30, 0xee, 0x3a, 0xd6,
	0xbb, 0xea, 0x66, 0x97, 0x06, 0x0f, 0xbf, 0xae, 0xeb, 0xef, 0x82, 0xa2, 0x75, 0xa1, 0x5b, 0xba,
	0xe8, 0xf8, 0x42, 0x5c, 0xa6, 0x09, 0x77, 0x3e, 0xa2, 0x54, 0x57, 0x53, 0x40, 0x70, 0xf5, 0x2e,
	0x15, 0xf7, 0x4e, 0x85, 0x3e, 0xd1, 0x6d, 0x25, 0x32, 0xa9, 0x7e, 0x36, 0x99, 0xa4, 0x42, 0x39,
	0x55, 0xea, 0xea, 0x92, 0xe9, 0x0b, 0x01, 0xfd, 0xfe, 0xd5, 0x03, 0x17, 0xdd, 0x68, 0x1c, 0x29,
	0xa7, 0x66, 0x09, 0x31, 0xae, 0x71, 0xea, 0x74, 0x47, 0xd7, 0x2e, 0x5f, 0x08, 0xb8, 0xba, 0x9b,
	0x40, 0x72, 0x67, 0xc5, 0x62, 0x84, 0xde, 0x32, 0xcd, 0x94, 0xb3, 0x6a, 0x9d, 0xd6, 0x81, 0x51,
	0x63, 0x24, 0xb8, 0x94, 0xce, 0x1a, 0xdd, 0xd3, 0xdd, 0xa2, 0x2f, 0x44, 0x3e, 0xba, 0x9e, 0xf4,
	0x3a, 0x4e, 0xc3, 0x62, 0x87, 0x8e, 0xa0, 0x3f, 0x95, 0x8a, 0x8f, 0x9d, 0x75, 0xfa, 0x94, 0xec,
	0x18, 0x74, 0x31, 0x20, 0x03, 0x3f, 0xb1, 0x8e, 0xfc, 0x8d, 0x08, 0x50, 0x46, 0xd3, 0xb2, 0xa4,
	0x60, 0xf6, 0x1f, 0x23, 0xe5, 0xb4, 0xe8, 0x33, 0xf2, 0xc4, 0x50, 0x60, 0xe2, 0x83, 0xf8, 0xd2,
	0x15, 0xd4, 0xd9, 0xb0, 0x14, 0x82, 0xca, 0xa9, 0x6b, 0x2b, 0x77, 0x36, 0x2d, 0x43, 0xcf, 0x82,
	0x64, 0xc8, 0x63, 0x1e, 0x3a, 0x5b, 0xf4, 0x53, 0xb2, 0x9f, 0x5b, 0x2f, 0xa2, 0x07, 0xd4, 0xc5,
	0xba, 0x4b, 0xc7, 0xd2, 0x00, 0x67, 0xe6, 0xcb, 0x54, 0x9d, 0xa7, 0x59, 0x12, 0x3a, 0xdb, 0xb6,
	0x06, 0xef, 0x64, 0x3b, 0x7d, 0x97, 0x40, 0xc7, 0xe6, 0x0b, 0xe1, 0x50, 0xeb, 0xa4, 0x13, 0x31,
	0xca, 0xc6, 0x3c, 0x51, 0xce, 0x0e, 0xfd, 0x84, 0x3c, 0x2b, 0xbc, 0x62, 0xc6, 0x80, 0xc2, 0xe5,
	0xce, 0xee, 0x21, 0xd3, 0xe6, 0xcf, 0x7a, 0x69, 0xba, 0x41, 0xd6, 0xcf, 0xae, 0x2e, 0xaf, 0x4f,
	0x3a, 0x97, 0x3e, 0x73, 0x3e, 0xa2, 0x0d, 0x52, 0xff, 0xe2, 0xaa, 0x7f, 0xed, 0x54, 0xe8, 0x3a,
	0x59, 0xe9, 0x5c, 0x9c, 0xfc, 0xd2, 0x77, 0xaa, 0xb4, 0x45, 0x1a, 0xbd, 0xee, 0xc9, 0xf5, 0xf9,
	0x15, 0xbb, 0x70, 0x6a, 0x74, 0x93, 0x90, 0xbe, 0xcf, 0x06, 0x3e, 0xeb, 0xfa, 0xfd, 0xbe, 0x53,
	0x3f, 0x7c, 0x41, 0x5a, 0xf6, 0x5c, 0x08, 0x12, 0x2f, 0x79, 0xf6, 0x80, 0xd1, 0xe8, 0x7c, 0x04,
	0xe0, 0xaf, 0xce, 0x45, 0x3a, 0x82, 0xfb, 0x76, 0x2a, 0x87, 0x17, 0x3a, 0x06, 0x8b, 0xcf, 0x2c,
	0xa0, 0xbf, 0x4d, 0x26, 0x81, 0x1a, 0xde, 0xf1, 0x50, 0xb3, 0x9f, 0x47, 0x8f, 0xfe, 0x63, 0x24,
	0x95, 0x74, 0x2a, 0x70, 0xd8, 0x57, 0x51, 0x1c, 0xc3, 0x8d, 0x44, 0x8f, 0x4e, 0x15, 0xe0, 0xb7,
	0x49, 0x70, 0x7b, 0xcb, 0x87, 0x8a, 0x87, 0x4e, 0xed, 0x66, 0x15, 0xbf, 0xdf, 0x5f, 0xfd, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x3d, 0x1d, 0x4b, 0x4e, 0x8c, 0x17, 0x00, 0x00,
}
